name: Build, Deploy and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-deploy-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Create logs directory
        run: mkdir -p logs

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check for Docker image changes
        id: check_changes
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          if echo "$CHANGED_FILES" | grep -q -E 'Dockerfile|requirements-prod.txt|api/|models/'; then
            echo "docker_changes=true" >> $GITHUB_OUTPUT
          else
            echo "docker_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and Push Docker image
        if: steps.check_changes.outputs.docker_changes == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/stackoverflow-predictor:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/stackoverflow-predictor:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/stackoverflow-predictor:buildcache,mode=max

      - name: Deploy to EC2
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            REMOTE_DIR="~/api-sof-project"
            mkdir -p "$REMOTE_DIR"
            cd "$REMOTE_DIR"

            # Disk space analysis
            echo "=== Disk Space Analysis ==="
            df -h
            echo "=== Docker Disk Usage ==="
            docker system df -v
            echo "=== Python Package Sizes ==="
            pip list --format=json | jq -r '.[] | "\(.name): \(.size) bytes"'

            # Docker Cleanup
            docker system prune -af --volumes
            docker builder prune -af

            # Container stop and removal
            if [ "$(docker ps -q)" ]; then
              docker stop $(docker ps -q)
            fi
            if [ "$(docker ps -aq)" ]; then
              docker rm $(docker ps -aq)
            fi

            # Repository cloning
            if [ -d ".git" ]; then
              git reset --hard
              git clean -fdx
              git pull origin main
            else
              git clone https://github.com/alinacharon/stackoverflow-tag-predictor.git .
            fi

            # Build Docker image with size analysis
            echo "=== Building Docker Image ==="
            docker build --no-cache --pull -t tag-predictor .
            echo "=== Final Image Size ==="
            docker images tag-predictor --format "{{.Size}}"

            # Run container with optimized settings
            docker run -d \
              --restart unless-stopped \
              --memory=3g \
              --memory-swap=4g \
              --memory-reservation=2g \
              --cpus=1 \
              --pids-limit=100 \
              -p 3000:3000 \
              -e PYTHONUNBUFFERED=1 \
              -e PYTHONDONTWRITEBYTECODE=1 \
              -e MODEL_LOAD_TIMEOUT=600 \
              --name tag-predictor \
              tag-predictor

            # Wait for container to be healthy
            echo "Waiting for container to be healthy..."
            timeout=600
            while [ $timeout -gt 0 ]; do
              if docker ps --filter "name=tag-predictor" --format "{{.Status}}" | grep -q "healthy"; then
                echo "Container is healthy!"
                break
              fi
              sleep 10
              timeout=$((timeout-10))
            done

            if [ $timeout -le 0 ]; then
              echo "Container failed to become healthy in time"
              docker logs tag-predictor
              exit 1
            fi

            # Final disk space check
            echo "=== Final Disk Space Usage ==="
            df -h
            echo "=== Final Docker Disk Usage ==="
            docker system df -v

      - name: Wait for server to be ready
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Waiting for server to be ready..."
          for i in {1..12}; do
            if curl -s -f http://${{ secrets.EC2_HOST }}:3000/health > /dev/null; then
              echo "Server is ready!"
              exit 0
            fi
            echo "Attempt $i: Server not ready yet..."
            sleep 15
          done
          echo "Server failed to start in time"
          exit 1

      - name: Run tests against deployed server
        if: github.ref == 'refs/heads/main'
        env:
          API_URL: http://${{ secrets.EC2_HOST }}:3000
        run: pytest tests/test_api.py -v
