name: Run Tests

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install tensorflow-cpu==2.15.0 tensorflow-hub==0.15.0

      - name: Verify model files
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Models directory contents:"
          ls -la models/
          echo "USE model directory contents:"
          ls -la models/use/
          echo "Checking if files are LFS pointers:"
          git lfs ls-files

      - name: Start API server
        run: |
          echo "Starting API server..."
          export TFHUB_CACHE_DIR="$(pwd)/models/use"
          echo "TFHUB_CACHE_DIR set to: $TFHUB_CACHE_DIR"
          echo "USE model directory contents:"
          ls -la $TFHUB_CACHE_DIR
          python -m uvicorn api.main:app --host 0.0.0.0 --port 3000 > server.log 2>&1 &
          echo "Waiting for server to start..."
          for i in {1..30}; do
            if curl -s http://localhost:3000/health > /dev/null; then
              echo "Server is up!"
              break
            fi
            echo "Attempt $i: Server not ready yet..."
            sleep 2
            if [ $i -eq 30 ]; then
              echo "Server failed to start. Logs:"
              cat server.log
              exit 1
            fi
          done

      - name: Run tests
        run: |
          echo "Running tests..."
          pytest tests/ -v
