name: Run Tests

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Pre-download USE model
        run: |
          echo "Pre-downloading USE model..."
          python -c "import tensorflow_hub as hub; hub.load('https://tfhub.dev/google/universal-sentence-encoder/4')"

      - name: Verify model files
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Models directory contents:"
          ls -la models/
          echo "Model file sizes:"
          du -h models/*.pkl
          echo "Checking if files are LFS pointers:"
          git lfs ls-files

      - name: Start API server
        run: |
          echo "Starting API server..."
          python -m uvicorn api.main:app --host 0.0.0.0 --port 3000 > server.log 2>&1 &
          echo "Waiting for server to start..."
          for i in {1..30}; do
            if curl -s http://localhost:3000/health > /dev/null; then
              echo "Server is up!"
              break
            fi
            echo "Attempt $i: Server not ready yet..."
            sleep 2
            if [ $i -eq 30 ]; then
              echo "Server failed to start. Logs:"
              cat server.log
              exit 1
            fi
          done

      - name: Run tests
        run: |
          echo "Running tests..."
          pytest tests/ -v
