name: Test and Build Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m nltk.downloader punkt averaged_perceptron_tagger wordnet stopwords

      - name: Create logs directory
        run: mkdir -p logs

      - name: Run tests
        run: pytest tests/test_api.py -v

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check for Docker image changes
        id: check_changes
        run: |
          # Get a list of modified files
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          # Check if the files affecting the Docker image have changed
          if echo "$CHANGED_FILES" | grep -q -E 'Dockerfile|requirements.txt|api/|models/'; then
            echo "docker_changes=true" >> $GITHUB_OUTPUT
          else
            echo "docker_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and Push Docker image
        if: steps.check_changes.outputs.docker_changes == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/stackoverflow-predictor:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/stackoverflow-predictor:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/stackoverflow-predictor:buildcache,mode=max
